version: '3.1'

services:
  mongodb:
    image: mongo
    restart: on-failure
    ports:
      - 27037:27017
    environment:
      MONGO_INITDB_DATABASE: api
    volumes:
      - dbvolume:/data/db

volumes:
  dbvolume: